### ISSUE TITLE
S33 plot

### ISSUE THREAD

**Issue by IoannisPantelis** [majroy/pyCM#14]
When asking pyCM to generate the line plot of longitudinal component (S33) of residual stresses, in mid-thickness of the weld [(100, 0),(-100,0)] a vertical line with zero value appears.

![image](https://user-images.githubusercontent.com/47006188/60022733-493f8c00-968c-11e9-9a80-7b1c1258bc25.png)

We manage to resolve this issue by slightly changing the value of y1 from 0 to -0,1 
[ (100,0), (-100,-0,1) ] and the correct M-Shape RS distribution was appeared, but it looks like it also changes the values and order of the X -axis.

![image1](https://user-images.githubusercontent.com/47006188/60023117-13e76e00-968d-11e9-87bb-9cdf83261f71.png)

Thank you in advance.

**Comment by NikStoyanov** [comment]
The stress components are extracted correctly, however, when you set the extraction Y coordinates to be zero as:

```
y1 = y2 = 0
```

The visualisation has a problem because it is assuming the points are along the Y coordinate https://github.com/majroy/pyCM/blob/d12696966128b7c50b0e738f36f1a8653f597ec5/pyCM/postprocess.py#L1019

In this case the code should be changed to
```python
plt.scatter(points[:,2], U[:]) 
```

But we really need a better way do to the interpolation. The path should be calculated using the Euclidean norm

![image](https://user-images.githubusercontent.com/28645743/60035391-9e879780-96a4-11e9-9609-174da2c1bea7.png)

And this should be what is plotted as the X axis in the output graph. I will add this to the code and run tests with it.

**Comment by NikStoyanov** [comment]
This issue is fixed now. I have added the Euclidean norm to be plotted in the extraction line in #15.

![image](https://user-images.githubusercontent.com/28645743/60336088-4d72ee80-9997-11e9-8639-3c6040a9f0a1.png)
