### ISSUE TITLE
Please advice; Error Message

### ISSUE THREAD

**Issue by damjamx** [majroy/pyCM#21]
Good day MajRoy,

I trust you are great. Please kindly advise. I get the error message in the screenshot below whenever I get to the Surface Fit tab and I can't fit the surfaces of already aligned and averaged data. This is the case wen I try to load the same MAT file. The raw input are raw data from a 3D scanner as .dat files with no outline.

![image](https://user-images.githubusercontent.com/46848851/82586754-f052cf00-9b4c-11ea-9c2c-b6dc7d28ca52.png)

Please kindly advice on what could be wrong. I look forward to hearing from you. 

Kind regards and stay safe!

**Comment by majroy** [comment]
Objects corresponding to a preprocessing step appear in the mat file ('pyCM pre couldn't read variables from file . . .'). I do not know how this may have occurred, other than there are read/write race conditions that can occur if the dataset is quite large.

Run the spline fitting routine outside of the main tabbed interface: https://github.com/majroy/pyCM/blob/master/doc/fit_surfaceREADME.md and then resume with either main, or the individual applications for pre and post processing. If the abberant datafile is not too large, please attach it here.

**Comment by damjamx** [comment]
Thank you very much. I also tried that but with no headway. Please kindly find attached the datafiles. 
[Datafiles - damjamx.zip](https://github.com/majroy/pyCM/files/4667549/Datafiles.-.damjamx.zip)


Kind regards

**Comment by majroy** [comment]
Please detail the issue encountered with running the spline fitting routine outside of the main tabbed interface, and the pyCM .mat file (not your raw data files) that you are trying to load that causes the issue described, please.

**Comment by damjamx** [comment]
Thank you very much. I will try to conduct the routine here now with the raw data available with me and update on the details as soon as possible. The routine was conducted on my office computer and I'm currently working from home. Thanks.

**Comment by damjamx** [comment]
Please find attached the screenshot when I tried running the spline fitting routine outside of the main tabbed interface. There is a prompt below which says "Grid too large" and I observed that I can't reduce the grid from the initial "0.00" which it was averaged on the main interface.

![image](https://user-images.githubusercontent.com/46848851/82667280-5e9a9e80-9bec-11ea-9a75-2da30482baf0.png)

The file is 25.4 MB. Please find the shared link below:

https://www.dropbox.com/sh/j735yjybrrkgj6v/AACahV166_prnCKqrAHUYDE_a?dl=0

Kind regards.

**Comment by majroy** [comment]
Your screen capture indicates that you are trying to apply a grid of knots spaced 4x4mm to a domain that is ~120µm in the x direction, and maybe 10µm in the y. So yes, your grid is too big. Regarding the '0' grid spacing in the alignment and averaging step, it's not zero, it's 2.5027e-03 µm, which is close enough to 0 for the UI.  I suspect that you have an incoming datafile with values in meters, instead of mm (see axis labels on the point editor). I recommend that you modify your raw data to be in mm, either that, or scale the modulus accordingly, if your data is indeed in meters.

I have found no issues with loading the file from the main interface, I do get a 'false' 'error' being reported by the pre-processor stating that it could not find a spline object, which is unsuprising given that there wasn't one in the file - this will be amended in the next release.
