### ISSUE TITLE
Sklearn deprecated

### ISSUE THREAD

**Issue by didiyang1** [majroy/pyCM#30]
During the installation, sklearn seems have been deprecated.

**Comment by majroy** [comment]
Due to the change in package name for scikit-learn (sklearn) **pyCMv2.0.0post1** fails to install sklearn. Specifically, running the main widget or the align/average widget will fail on 'ModuleNotFoundError' when it comes to sklearn if it has not been previously installed.

Immediate remedy for this version is to run `pip install scikit-learn` immediately after installation. For safety, it is advised to also run `pip uninstall sklearn`. See this release for an explanation: https://pypi.org/project/sklearn/

**Comment by majroy** [comment]
Closed issue as updated package name will be included for new version or as part of a general bugfix.

**Comment by majroy** [comment]
Re-opened for discoverability, will close when new release available.

**Comment by majroy** [comment]
Fixed now with v2.0.0post2.
